---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
spec:
  interval: 1m0s
  ref:
    ${ref=branch: main}
  url: https://github.com/sparhomenko/homelab.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: ConfigMap
        name: flux-config
        optional: true
