---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/fluxcd/flux2/manifests/install?ref=v2.1.1
patches:
  - target:
      labelSelector: app.kubernetes.io/component in (notification-controller,image-reflector-controller,image-automation-controller)
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          config.kubernetes.io/local-config: "true"
