---
name: CI
on: [push] # yamllint disable-line rule:truthy
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: v1.3.4 # renovate github-releases:hashicorp/terraform
      - name: Init Terraform
        run: terraform init -lockfile=readonly
      - name: Validate Terraform files
        run: terraform validate
      - name: Check Terraform file formatting
        run: terraform fmt -check -diff -recursive
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2.0.1
        with:
          tflint_version: v0.42.2 # renovate github-releases:terraform-linters/tflint
      - name: TFLint
        run: tflint --module
  gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          strict: true
      - name: Lint Kubernetes manifests
        uses: docker://ghcr.io/yannh/kubeconform:v0.5.0
        with:
          entrypoint: /kubeconform
          args: >
            -strict
            -kubernetes-version ${{ env.KUBERNETES_VERSION }}
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            gitops
        env:
          KUBERNETES_VERSION: 1.25.3 # renovate github-releases:kubernetes/kubernetes
  test:
    runs-on: ubuntu-latest
    needs: [terraform, gitops]
    services:
      talos:
        image: ghcr.io/siderolabs/talos:v1.2.6
        env:
          PLATFORM: container
        volumes: ["vol1:/etc/cni", "vol2:/run", "vol3:/var/lib/containerd", "vol4:/var/lib/kubelet"]
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: v1.3.4 # renovate github-releases:hashicorp/terraform
      - name: Init Terraform
        run: terraform init -lockfile=readonly
        working-directory: terraform
      - name: Apply Terraform scripts
        run: |
          IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ job.services.talos.id }})
          terraform apply -auto-approve -var "nodes=[\"$IP\"]" -target module.argocd.kubectl_manifest.main
          terraform apply -auto-approve -var "nodes=[\"$IP\"]"
        working-directory: terraform
