---
name: CI
on: [push] # yamllint disable-line rule:truthy
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          strict: true
      - name: Install Flux CLI
        uses: fluxcd/flux2/action@v2.1.0
      - name: Build Kustomize resources
        run: flux build kustomization flux-system --dry-run --kustomization-file flux/gotk-sync.yaml --path . > gitops.yaml
      # TODO: consider 'helm template' or 'flux build helmrelease --dry-run' (https://github.com/fluxcd/flux2/issues/2808)
      - name: Lint Kubernetes manifests
        uses: docker://ghcr.io/yannh/kubeconform:v0.6.3
        with:
          entrypoint: /kubeconform
          args: >
            -strict
            -kubernetes-version ${{ env.KUBERNETES_VERSION }}
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            -skip CustomResourceDefinition
            gitops.yaml
        env:
          KUBERNETES_VERSION: 1.28.1 # renovate github-releases:kubernetes/kubernetes:^v(?<version>.*)$
      - name: Create cluster # TODO: cache something to speed up (2-2.5m)
        run: |
          curl -Lo talosctl --no-progress-meter https://github.com/siderolabs/talos/releases/download/${{ env.TALOS_VERSION }}/talosctl-$(uname -s | tr '[:upper:]' '[:lower:]')-$(dpkg --print-architecture)
          chmod +x talosctl
          ./talosctl cluster create \
            --workers 0 \
            --config-patch-control-plane '{cluster: {allowSchedulingOnControlPlanes: true}}' \
            --kubernetes-version "${{ env.KUBERNETES_VERSION }}"
        env:
          TALOS_VERSION: v1.5.2 # renovate github-releases:siderolabs/talos
          KUBERNETES_VERSION: v1.28.1 # renovate github-releases:kubernetes/kubernetes
      - name: Configure GitOps
        run: |
          kubectl apply -f flux/gotk-components.yaml # Install Flux CRDs before using them

          ref='commit: ${{ github.sha }}'
          kubectl create configmap flux-config -n flux-system --from-literal "ref=$ref"
          sed -i='' "s/\${ref=branch: main}/$ref/" flux/gotk-sync.yaml
          kubectl apply -k flux

          kubectl wait deployment -n flux-system --for condition=Available -l 'app.kubernetes.io/part-of=flux'
          flux reconcile kustomization flux-system --with-source --timeout 1m
      - name: Extract debug info
        if: failure()
        run: |
          flux get all -A
          flux events -A
